version: "3.9"
services:

  #  my app
  app:
    build: .
    container_name: eshop-springboot-app
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://eshop-mysql:3306/eshop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678

      SPRING_DATA_REDIS_HOST: eshop-redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_ELASTICSEARCH_URIS: http://eshop-elasticsearch:9200

      SPRING_RABBITMQ_HOST: eshop-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

    depends_on:
      - mysql
      - redis
      - elasticsearch
      - rabbitmq
  #my sql
  mysql:
    image: mysql:8.0
    container_name: eshop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: eshop
    ports:
      - "3307:3306"   # cổng host 3307 -> container 3306
    volumes:
      - mysql_data:/var/lib/mysql

  #redis
  redis:
    image: redis:7.2
    container_name: eshop-redis
    ports:
      - "6379:6379"

  #liquibase
  liquibase:
    image: liquibase
    container_name: eshop-liquibase
    depends_on:
      - mysql
    environment:
      LIQUIBASE_URL: jdbc:mysql://eshop-mysql:3306/eshop
      LIQUIBASE_USERNAME: root
      LIQUIBASE_PASSWORD: 12345678
      LIQUIBASE_CHANGELOG_FILE: /liquibase/changelog/master.xml
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog

    # elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.2
    container_name: eshop-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data   # ✅ mount volume để dữ liệu không mất khi restart

  # kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.2
    container_name: eshop-kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://eshop-elasticsearch:9200   # ✅ chỉ định ES host
    depends_on:
      - elasticsearch   # ✅ Kibana cần ES chạy trước
  #rabitmq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: eshop-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql_data:
  es_data:

networks:
  eshop-network:
    driver: bridge